# Copyright (C) 2018 Inuvika Inc.
# https://www.inuvika.com
# Author David PHAM-VAN <d.phamvan@inuvika.com> 2018
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Check the OS version
  assert:
    that:
      - ansible_distribution_major_version == '7'
    msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported by OVD {{ ovd_version_detected }}"

- block:
  - name: Install the EPEL repository
    yum:
      name: "{{ epel7_url }}"
      state: present

- block:
  - name: Install the subscription-manager package
    yum:
      name: subscription-manager
      state: present
  - name: Enable the Optional Repository Channel
    command: subscription-manager repos --enable=rhel-7-server-optional-rpms
  when: ansible_distribution in ['RedHat', 'Red Hat Enterprise Linux']

- name: Add OVD Repository
  yum_repository:
    name: ovd-{{ ovd_version_detected }}
    description: Inuvika OVD {{ ovd_version_detected }}
    baseurl: '{{ ovd_repo }}/rhel/{{ ansible_distribution_major_version }}/'
    gpgkey: '{{ ovd_repo }}/keyring'
    gpgcheck: yes
    state: present
    file: ovd

- name: "SELinux : Install tool for configuration"
  yum:
    name: policycoreutils-python

- name: "SELinux Apache-fpm : Configuration"
  when: ovd_www_config == 'apache-fpm'
  block:
    - name: "SELinux : Deploy policy"
      block:
      - name: "SELinux : Deploy policy : Copy policy to host"
        copy:
          src: ovd_php-fpm.te
          dest: /tmp/ovd_php-fpm.te

      - name: "SELinux : Deploy policy : Create type file"
        command: checkmodule -M -m -o /tmp/ovd_php-fpm.mod /tmp/ovd_php-fpm.te

      - name: "SELinux : Deploy policy : Package policy"
        command: semodule_package -o /tmp/ovd_php-fpm.pp -m /tmp/ovd_php-fpm.mod

      - name: "SELinux : Deploy policy : Install policy"
        command: semodule -i /tmp/ovd_php-fpm.pp


# - name: "SELinux other policies"
#   block:
#     - name: "SELinux : Deploy policy"
#       block:
#       - name: "SELinux : Deploy policy : Copy policy to host"
#         copy:
#           src: ovd_other.te
#           dest: /tmp/ovd_other.te

#       - name: "SELinux : Deploy policy : Create type file"
#         command: checkmodule -M -m -o /tmp/ovd_other.mod /tmp/ovd_other.te

#       - name: "SELinux : Deploy policy : Package policy"
#         command: semodule_package -o /tmp/ovd_other.pp -m /tmp/ovd_other.mod

#       - name: "SELinux : Deploy policy : Install policy"
#         command: semodule -i /tmp/ovd_other.pp
